- id: '1608774094962'
  alias: Weekdays - Open Shutters
  description: ''
  trigger:
  - platform: time
    at: 09:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id:
      - cover.bedroom_shutter
      - cover.bureau_shutter
  mode: single
- id: '1609972900027'
  alias: Daily - Everything OFF
  description: ''
  trigger:
  - platform: time
    at: 02:00
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bedroom_main
      - light.bedroom_sidelights
      - light.bureau_lights
      - light.bureau_main
      - light.guest_room_main
      - light.diner_filaments
      - light.kitchen_lamp
      - light.living_room_lamp
      - light.torch_lamp
      - light.closet_lamp
      - light.tripod_lamp
      - light.bloom_mobile
      - light.bloom_tv
      - light.patio_spots
      - light.hallway_downstairs
      - light.hallway_spots
  - service: switch.turn_off
    target:
      entity_id:
      - switch.garden_lights
      - switch.kitchen_lights
  mode: single
- id: '1609974493789'
  alias: Daily - Driveway & Garden Lights - Midnight
  description: Set lights to 20%
  trigger:
  - platform: time
    at: 00:00
  condition: []
  action:
  - scene: scene.driveway_garden_lights_after_midnight
  mode: single
- id: '1609974785728'
  alias: Daily - Driveway & Garden Lights - Sunrise
  description: Everything OFF
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.driveway_door_lights
      - light.garden_outside
  mode: single
- id: '1609975184621'
  alias: Daily - Driveway & Garden Lights - Sunset
  description: Set lights to 50%
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - scene: scene.driveway_garden_lights_after_sunset
  mode: single
- id: '1618259026456'
  alias: Daily - Living Room Evening Lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-1:00'
  condition: []
  action:
  - scene: scene.living_room_lighting
  mode: single
- id: '1628538980655'
  alias: Daily - Close Shutters
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30
  condition: []
  action:
  - service: cover.close_cover
    target:
      entity_id:
      - cover.bedroom_shutter
      - cover.bureau_shutter
  mode: single
- id: '1628539023619'
  alias: Weekends - Open Shutters
  description: ''
  trigger:
  - platform: time
    at: '11:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id:
      - cover.bedroom_shutter
      - cover.bureau_shutter
  mode: single
- id: '1630148105598'
  alias: Auto - Turn on AC when Temperature > 21C
  description: Fires between 22:00 - 08:00
  trigger:
  - platform: numeric_state
    entity_id: sensor.bedroom_ac_current_temp
    above: '21'
    for: 00:30:00
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: zone
        entity_id: person.aimee
        zone: zone.home
      - condition: zone
        entity_id: person.fabian
        zone: zone.home
    - condition: time
      after: '22:00'
      before: 08:00
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.bedroom_ac_cool
  - service: climate.set_swing_mode
    target:
      entity_id: climate.bedroom_ac
    data:
      swing_mode: '4'
  - service: climate.set_fan_mode
    target:
      entity_id: climate.bedroom_ac
    data:
      fan_mode: '1'
  - service: climate.set_temperature
    target:
      entity_id: climate.bedroom_ac
    data:
      temperature: 20
  mode: single
- id: '1630168235518'
  alias: Auto - Turn off AC when Temperature reached
  description: ''
  trigger:
  - platform: template
    value_template: '{{ state_attr(''climate.bedroom_ac'', ''current_temperature'')
      | float < state_attr(''climate.bedroom_ac'', ''temperature'') | float }}

      '
    for: 00:30:00
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: climate.bedroom_ac
      state: 'off'
      for: 00:60:00
  action:
  - service: climate.turn_off
    target:
      entity_id: climate.bedroom_ac
  mode: single
- id: '1630329112838'
  alias: Kitchen Switch
  description: ''
  use_blueprint:
    path: myGithub-Markus/deconz_friends_of_hue_smart_switch_fourfold_button.yaml
    input:
      remote: 58686bd8201c2500456c8a853473211a
      button_one_single_press:
      - service: light.turn_on
        target:
          entity_id: light.kitchen_lights
      button_two_single_press:
      - service: light.turn_off
        target:
          entity_id: light.kitchen_lights
      button_three_single_press:
      - service: light.turn_on
        target:
          entity_id: light.kitchen_lamp
      button_four_single_press:
      - service: light.turn_off
        target:
          entity_id: light.kitchen_lamp
      button_four_hold_in:
      - repeat:
          count: '30'
          sequence:
          - device_id: 3c185ddd2c9feadf022a575a8d345a81
            domain: light
            entity_id: light.kitchen_spot_1
            type: brightness_decrease
          - device_id: e836e81e18dc6f85bbbc3f99ed08fa3f
            domain: light
            entity_id: light.kitchen_spot_2
            type: brightness_decrease
          - device_id: 10e90f8f5fd8fbcad622ee22cef71d77
            domain: light
            entity_id: light.kitchen_spot_3
            type: brightness_decrease
      button_three_hold_in:
      - repeat:
          count: '30'
          sequence:
          - device_id: 3c185ddd2c9feadf022a575a8d345a81
            domain: light
            entity_id: light.kitchen_spot_1
            type: brightness_increase
          - device_id: e836e81e18dc6f85bbbc3f99ed08fa3f
            domain: light
            entity_id: light.kitchen_spot_2
            type: brightness_increase
          - device_id: 10e90f8f5fd8fbcad622ee22cef71d77
            domain: light
            entity_id: light.kitchen_spot_3
            type: brightness_increase
