- id: "1608774094962"
  alias: Daily Shutters - Open
  description: ""
  trigger:
    - platform: time
      at: "12:00"
  condition: []
  action:
    - service: cover.open_cover
      data: {}
      entity_id: cover.bedroom_shutter
    - service: cover.open_cover
      data: {}
      entity_id: cover.bureau_shutter
  mode: single
- id: "1608774150395"
  alias: Daily Shutters - Close
  description: ""
  trigger:
    - platform: sun
      event: sunset
      offset: 00:15
  condition: []
  action:
    - service: cover.close_cover
      data: {}
      entity_id: cover.bedroom_shutter
    - service: cover.close_cover
      data: {}
      entity_id: cover.bureau_shutter
  mode: single
- id: play_radio
  alias: Play Radio
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.favorites
  action:
    - service:
        "{% if is_state(\"input_select.favorites\", \"Off\") %}\n    media_player.media_stop\n\
        \  {% else %}\n    media_player.select_source\n  {% endif %}\n"
      entity_id: media_player.bureau
      data_template:
        source:
          '{% if not is_state("input_select.favorites", "Off") %} {{ states.input_select.favorites.state
          }} {% else %} {% endif %}

          '
- id: "1609972081340"
  alias: Turn off Floorlight
  description: ""
  trigger:
    - device_id: 84aec03607d50505dbf3004df6b83a3f
      domain: hue
      platform: device
      type: remote_button_short_press
      subtype: button_4
  condition: []
  action:
    - service: switch.turn_off
      data: {}
      entity_id: switch.floorlight
  mode: single
- id: "1609972192616"
  alias: Turn on Floorlight
  description: ""
  trigger:
    - device_id: 84aec03607d50505dbf3004df6b83a3f
      domain: hue
      platform: device
      type: remote_button_short_press
      subtype: button_3
  condition:
    - condition: or
      conditions:
        - condition: sun
          after: sunset
        - condition: sun
          before: sunrise
  action:
    - service: switch.turn_on
      data: {}
      entity_id: switch.floorlight
  mode: single
- id: "1609972900027"
  alias: Daily - Everything OFF
  description: ""
  trigger:
    - platform: time
      at: 02:00
  condition: []
  action:
    - service: remote.turn_off
      data: {}
      entity_id: remote.harmony_living_room
    - service: light.turn_off
      entity_id: light.bathroom
    - service: light.turn_off
      entity_id: light.bedroom
    - service: light.turn_off
      entity_id: light.bureau
    - service: light.turn_off
      entity_id: light.guest_room
    - service: light.turn_off
      entity_id: light.hallway
    - service: light.turn_off
      entity_id: light.living_room
    - service: light.turn_off
      entity_id: light.kitchen
    - service: light.turn_off
      entity_id: light.toilet
    - service: switch.turn_off
      data: {}
      entity_id: switch.floorlight
  mode: single
- id: "1609974493789"
  alias: Daily - Driveway & Garden Lights - Midnight
  description: Set lights to 20%
  trigger:
    - platform: time
      at: 0:00
  condition: []
  action:
    - scene: scene.driveway_garden_lights_after_midnight
  mode: single
- id: "1609974785728"
  alias: Daily - Driveway & Garden Lights - Sunrise
  description: Everything OFF
  trigger:
    - platform: sun
      event: sunrise
  condition: []
  action:
    - service: light.turn_off
      data: {}
      entity_id: light.driveway
    - service: light.turn_off
      data: {}
      entity_id: light.garden
  mode: single
- id: "1609975184621"
  alias: Daily - Driveway & Garden Lights - Sunset
  description: Set lights to 50%
  trigger:
    - platform: sun
      event: sunset
  condition: []
  action:
    - scene: scene.driveway_garden_lights_after_sunset
  mode: single
- id: "1610038641208"
  alias: Subwoofer OFF
  description: ""
  trigger:
    - platform: state
      entity_id: remote.harmony_living_room
      to: "off"
  condition: []
  action:
    - service: switch.turn_off
      data: {}
      entity_id: switch.subwoofer
  mode: single
- id: "1610038849104"
  alias: Subwoofer ON
  description: ""
  trigger:
    - platform: state
      entity_id: remote.harmony_living_room
      to: "on"
  condition: []
  action:
    - service: switch.turn_on
      data: {}
      entity_id: switch.subwoofer
  mode: single
