- id: harmony
  alias: Harmony
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.harmony
  action:
  - service: remote.turn_on
    entity_id: remote.harmonyhub
    data_template:
      activity: "{% if is_state(\"input_select.harmony\", \"TV\") %}\n  31071270\n\
        {% elif is_state(\"input_select.harmony\", \"Movies\") %}\n  31074811\n{%\
        \ elif is_state(\"input_select.harmony\", \"View Mac mini\") %}\n  31071271\n\
        {% else %}\n  -1\n{% endif %}\n"
- id: harmony_update
  alias: Harmony Update
  hide_entity: true
  trigger:
    platform: state
    entity_id: remote.harmonyhub
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.harmony
      option: "{% if states.remote.harmonyhub.attributes.current_activity == \"PowerOff\"\
        \ %}\n  Powered Off\n{% else %}\n  {{ states.remote.harmonyhub.attributes.current_activity\
        \ }}\n{% endif %}\n"
- id: battery_status_update
  alias: Battery Status Update
  trigger:
  - platform: time
    minutes: /5
    seconds: 0
  action:
    service: input_boolean.toggle
    data:
      entity_id: input_boolean.battery_status_update_bool
- id: battery_status
  alias: Battery Status
  trigger:
  - platform: time
    at: '10:00:00'
  - platform: time
    at: '16:45:00'
  condition:
    condition: template
    value_template: '{% if states(''sensor.battery_status'') %}{{ true }}{% else %}{{
      false }}{% endif %}'
  action:
  - service: persistent_notification.create
    data_template:
      title: Low Battery levels
      message: '{{ states(''sensor.battery_status'') }}'
      notification_id: low-battery-alert
- id: '1539012359670'
  alias: Battery Full
  trigger:
  - entity_id: sensor.330e_iperformance_charging_level_hv
    platform: state
  condition:
  - condition: state
    entity_id: sensor.330e_iperformance_charging_level_hv
    state: '100'
  action:
  - service: notify.notify
    data:
      title: Car fully charged
      message: Car is fully charged at {{ states('sensor.330e_iperformance_charging_level_hv')
        }}%
  # - service: persistent_notification.create
  #   data:
  #     title: Car fully charged
  #     message: Car is fully charged at {{ states('sensor.330e_iperformance_charging_level_hv')
  #       }}%
  #     notification_id: fully_charged_car
- id: battery_charge_error
  alias: Battery Charge Error
  trigger:
  - entity_id: sensor.bmw_connectioncharge_status
    platform: state
  condition:
  - condition: state
    entity_id: sensor.bmw_connectioncharge_status
    state: 'ERROR'
  action:
  - service: notify.notify
    data:
      message: Car is not charging due to connection error
      title: Car not charging