- id: '1608774094962'
  alias: Daily Shutters - Open
  description: ''
  trigger:
  - platform: time
    at: '11:00'
  condition: []
  action:
  - service: cover.open_cover
    data: {}
    entity_id: cover.bedroom_shutter
  mode: single
- id: '1608774150395'
  alias: Daily Shutters - Close
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 00:15
  condition: []
  action:
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.bedroom_shutter
  - service: cover.close_cover
    data: {}
    target:
      entity_id: cover.bureau_shutter
  mode: single
- id: play_radio
  alias: Play Radio
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_select.favorites
  action:
  - service: "{% if is_state(\"input_select.favorites\", \"Off\") %}\n    media_player.media_stop\n\
      \  {% else %}\n    media_player.select_source\n  {% endif %}\n"
    entity_id: media_player.bureau
    data_template:
      source: '{% if not is_state("input_select.favorites", "Off") %} {{ states.input_select.favorites.state
        }} {% else %} {% endif %}

        '
- id: '1609972081340'
  alias: Turn off - Floorlight
  description: ''
  trigger:
  - device_id: 84aec03607d50505dbf3004df6b83a3f
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_4
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.floorlight
  mode: single
- id: '1609972192616'
  alias: Turn on - Floorlight
  description: ''
  trigger:
  - device_id: 84aec03607d50505dbf3004df6b83a3f
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_3
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.floorlight
  mode: single
- id: '1609972900027'
  alias: Daily - Everything OFF
  description: ''
  trigger:
  - platform: time
    at: 02:00
  condition: []
  action:
  - service: remote.turn_off
    data: {}
    entity_id: remote.harmony_living_room
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bedroom_main
      - light.bedroom_sidelights
      - light.bureau_lights
      - light.bureau_main
      - light.guest_room_main
      - light.diner_filaments
      - light.hallway_spots
      - light.hallway_lamp
      - light.hue_go_one
      - light.hue_go_tv
      - light.ikea_lamp
      - light.kitchen_lamp
      - light.living_room_lamp
  - service: switch.turn_off
    target:
      entity_id:
      - switch.floorlight
      - switch.garden_lights
      - switch.harmony_living_room_tv
      - switch.kitchen_lights
      - switch.salt_lamp
  mode: single
- id: '1609974493789'
  alias: Daily - Driveway & Garden Lights - Midnight
  description: Set lights to 20%
  trigger:
  - platform: time
    at: 0:00
  condition: []
  action:
  - scene: scene.driveway_garden_lights_after_midnight
  mode: single
- id: '1609974785728'
  alias: Daily - Driveway & Garden Lights - Sunrise
  description: Everything OFF
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.driveway_door_lights
      - light.garden_outside
  mode: single
- id: '1609975184621'
  alias: Daily - Driveway & Garden Lights - Sunset
  description: Set lights to 50%
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - scene: scene.driveway_garden_lights_after_sunset
  mode: single
- id: '1610038641208'
  alias: Subwoofer OFF
  description: ''
  trigger:
  - platform: state
    entity_id: remote.harmony_living_room
    to: 'off'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.subwoofer
  mode: single
- id: '1610038849104'
  alias: Subwoofer ON
  description: ''
  trigger:
  - platform: state
    entity_id: remote.harmony_living_room
    to: 'on'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.subwoofer
  mode: single
- id: '1615329439213'
  alias: Kitchen Lights - Turn on
  description: ''
  trigger:
  - device_id: 78d3173dfeb7623b2b343bac58059626
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    entity_id: switch.kitchen_lights
  mode: single
- id: '1615329479726'
  alias: Kitchen Lights - Turn off
  description: ''
  trigger:
  - device_id: 78d3173dfeb7623b2b343bac58059626
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    entity_id: switch.kitchen_lights
  mode: single
- id: '1616083063299'
  alias: Turn on - Salt Lamp
  description: ''
  trigger:
  - device_id: 0ebc63631c79382336aa98c33cfab803
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.salt_lamp
  mode: single
- id: '1616083103638'
  alias: Turn off - Salt Lamp
  description: ''
  trigger:
  - device_id: 0ebc63631c79382336aa98c33cfab803
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id: switch.salt_lamp
  mode: single
- id: '1616754008519'
  alias: Aimee Home
  description: ''
  trigger:
  - platform: device
    device_id: 84476d7bb4d60e9482f8f290035012ab
    domain: device_tracker
    entity_id: device_tracker.iphone_van_aimee
    type: enters
    zone: zone.home
  condition: []
  action:
  - service: scene.create
    data:
      scene_id: before
      snapshot_entities:
      - light.bureau_light_left
      - light.bureau_light_right
  - service: light.turn_on
    data:
      flash: short
      rgb_color:
      - 252
      - 3
      - 3
    target:
      entity_id:
      - light.bureau_light_left
      - light.bureau_light_right
  - delay: 5
  - service: scene.turn_on
    entity_id: scene.before
  mode: single
- id: '1618259026456'
  alias: Daily - Living Room Evening Lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-1:00'
  condition: []
  action:
  - scene: scene.living_room_lighting
  mode: single
- id: '1618390213380'
  alias: Open Bureau Shutter
  description: Daily
  trigger:
  - platform: time
    at: '9:00'
  condition: []
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.bureau_shutter
  mode: single
