- id: '1608774094962'
  alias: Weekdays - Open Shutters
  description: ''
  trigger:
  - platform: time
    at: 09:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id:
      - cover.bedroom_shutter
      - cover.bureau_shutter
  mode: single
- id: '1609972900027'
  alias: Daily - Everything OFF
  description: ''
  trigger:
  - platform: time
    at: 02:00
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.bedroom_main
      - light.bedroom_sidelights
      - light.bureau_lights
      - light.bureau_main
      - light.guest_room_main
      - light.diner_filaments
      - light.kitchen_lamp
      - light.living_room_lamp
      - light.torch_lamp
      - light.closet_lamp
      - light.tripod_lamp
      - light.bloom_mobile
      - light.bloom_tv
      - light.patio_spots
      - light.hallway_downstairs
      - light.hallway_spots
  - service: switch.turn_off
    target:
      entity_id:
      - switch.garden_lights
      - switch.kitchen_lights
  mode: single
- id: '1609974493789'
  alias: Daily - Driveway & Garden Lights - Midnight
  description: Set lights to 20%
  trigger:
  - platform: time
    at: 00:00
  condition: []
  action:
  - scene: scene.driveway_garden_lights_after_midnight
  mode: single
- id: '1609974785728'
  alias: Daily - Driveway & Garden Lights - Sunrise
  description: Everything OFF
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.driveway_door_lights
      - light.garden_outside
  mode: single
- id: '1609975184621'
  alias: Daily - Driveway & Garden Lights - Sunset
  description: Set lights to 50%
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - scene: scene.driveway_garden_lights_after_sunset
  mode: single
- id: '1618259026456'
  alias: Daily - Living Room Evening Lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: '-1:00'
  condition: []
  action:
  - scene: scene.living_room_lighting
  mode: single
- id: '1628538980655'
  alias: Daily - Close Shutters
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30
  condition: []
  action:
  - service: cover.close_cover
    target:
      entity_id:
      - cover.bedroom_shutter
      - cover.bureau_shutter
  mode: single
- id: '1628539023619'
  alias: Weekends - Open Shutters
  description: ''
  trigger:
  - platform: time
    at: '11:00'
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - service: cover.open_cover
    data: {}
    target:
      entity_id:
      - cover.bedroom_shutter
      - cover.bureau_shutter
  mode: single
- id: '1628809570878'
  alias: AC Night Mode
  description: ''
  trigger:
  - platform: time
    at: 02:00
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: climate.bedroom_ac
      state: 'off'
  action:
  - service: climate.set_swing_mode
    target:
      entity_id: climate.bedroom_ac
    data:
      swing_mode: '4'
  - service: climate.set_fan_mode
    target:
      entity_id: climate.bedroom_ac
    data:
      fan_mode: '1'
  mode: single
- id: '1628809813949'
  alias: AC Off
  description: ''
  trigger:
  - platform: time
    at: 06:00
  condition:
  - condition: not
    conditions:
    - condition: state
      entity_id: climate.bedroom_ac
      state: 'off'
  action:
  - service: climate.turn_off
    target:
      entity_id: climate.bedroom_ac
  mode: single
- id: '1629390803465'
  alias: Kitchen Lights - On
  description: ''
  trigger:
  - device_id: f092c53c1c768d1f360584ec4c6c0526
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_1
  condition: []
  action:
  - type: turn_on
    device_id: ca5118ba46385b003967b1b094061ff1
    entity_id: switch.kitchen_lights
    domain: switch
  mode: single
- id: '1629390854289'
  alias: Kitchen Lights - Off
  description: ''
  trigger:
  - device_id: f092c53c1c768d1f360584ec4c6c0526
    domain: hue
    platform: device
    type: remote_button_short_press
    subtype: button_2
  condition: []
  action:
  - type: turn_off
    device_id: ca5118ba46385b003967b1b094061ff1
    entity_id: switch.kitchen_lights
    domain: switch
  mode: single
