homeassistant:
  auth_providers:
    - type: homeassistant
  # Name of the location where Home Assistant is running
  name: iHouse
  # Location required to calculate the time the sun rises and sets
  latitude: 51.4212
  longitude: 5.4579
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 17
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: https://ihouse:8321
  # pihole:
  #   title: Pi-hole
  #   icon: mdi:block-helper
  #   url: https://ihouse:4865/admin/index.php