# Text to speech
# tts:
#   - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  external_url: https://ihaduckdns.duckdns.org
  internal_url: http://192.168.1.174:8123
  
  packages: !include_dir_named packages
  customize: !include customize.yaml
  time_zone: Europe/Amsterdam
