automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  base_url: !secret external_url

homeassistant:
  external_url: !secret external_url
  internal_url: !secret internal_url

  packages: !include_dir_named packages
  customize: !include customize.yaml
  name: iHouse
  time_zone: Europe/Amsterdam
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 20
