title: Home

# custom_header:
#   !include /config/lovelace/custom_header.yaml

# Button card templates
decluttering_templates:
  #!include /config/lovelace/decluttering_templates/decluttering_templates.yaml
  !include_dir_merge_named /config/lovelace-library/templates/decluttering_templates/

button_card_templates:
  !include lovelace/button_card_templates/button_card_templates.yaml
  # !include_dir_merge_named /config/lovelace-library/templates/button_card_templates/

background: var(--background-image)
views: !include_dir_merge_list lovelace/views/
#dsfjklsdfjklsdfakjladsdssdfdfs
