title: Home

# custom_header:
#   !include /config/lovelace/custom_header.yaml

# Button card templates
decluttering_templates: !include_dir_merge_named /config/lovelace-library/templates/decluttering_templates/

button_card_templates: !include_dir_merge_named /config/lovelace-library/templates/button_card_templates/

background: var(--background-image)
views:
  ### VISIBLE VIEWS
  # Maindssffsdfdssfdsdffdsdfsa
  - !include /config/lovelace-library/tabs/view_main.yaml
  # Cameras
  - !include /config/lovelace-library/tabs/view_cameras.yaml
  # Scenes
  - !include /config/lovelace-library/tabs/view_scenes.yaml
  # Media
  - !include /config/lovelace-library/tabs/view_media.yaml
  # More
  - !include /config/lovelace-library/tabs/view_more.yaml

  ### NOT VISIBLE, ONLY NAVIGATION - DEVICES
  # Climate
  - !include /config/lovelace-library/tabs/view_climate.yaml
  # Shutters
  - !include /config/lovelace-library/tabs/view_shutters.yaml
  # Lights
  - !include /config/lovelace-library/tabs/view_lights.yaml
  # Energy
  - !include /config/lovelace-library/tabs/view_energy.yaml
  # Batteries
  - !include /config/lovelace-library/tabs/view_batteries.yaml

  ### NOT VISIBLE, ONLY NAVIGATION - ROOMS
  # Rooms
  - !include /config/lovelace-library/tabs/view_rooms.yaml
  # Living Room
  - !include /config/lovelace-library/tabs/view_living_room.yaml
  # Kitchen
  - !include /config/lovelace-library/tabs/view_kitchen.yaml
  # Bureau
  - !include /config/lovelace-library/tabs/view_bureau.yaml
  # Bedroom
  - !include /config/lovelace-library/tabs/view_bedroom.yaml
  # Guest Room
  - !include /config/lovelace-library/tabs/view_guest_room.yaml
  # Hallway
  - !include /config/lovelace-library/tabs/view_hallway.yaml
  # Garden
  - !include /config/lovelace-library/tabs/view_outside.yaml
