############# MOVE FROM "custom_updater" TO "HACS"!!! ##########################
## https://custom-components.github.io/hacs/
## BASICALLY YOU NEED TO ADD EVERY CUSTOM REPO TO HACS 
## AND CHANGE ALL URL FROM:" /customcards/custom_lovelace_cards/XXXXXXXXX"
## TO "/community_plugin/XXXXXXXXX/XXXXXXXXX.js" 
## More info at: https://custom-components.github.io/hacs/#add-custom-repos
################################################################################

#################################################################
#                             JS                                #
################################################################# 
resources: 
## https://github.com/thomasloven/lovelace-card-modder 
  - url: /community_plugin/lovelace-card-modder/card-modder.js
    type: js
## https://github.com/thomasloven/lovelace-card-tools
  - url: /community_plugin/lovelace-card-tools/card-tools.js    
    type: js
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: module
    
title: iHouse
views:
  - title: default_view
    icon: mdi:home
    cards:
      - type: entities
        title: Entrance
        show_header_toggle: true
        entities:
          - light.entrance_lamp
      - type: entities
        title: Living Room
        show_header_toggle: true
        entities:
          - light.diner_lamp
          - group.livingroom_tv_lights
          - group.ikea_lights
      - type: entities
        title: Bureau
        show_header_toggle: true
        entities:
          - group.bureau_lights
      - type: entities
        title: Kitchen
        show_header_toggle: true
        entities:
          - group.kitchen_lights
      - type: entities
        title: Bedroom
        show_header_toggle: true
        entities:
          - group.bedroom_sidelights_group
      - type: entities
        title: Bathroom
        show_header_toggle: true
        entities:
          - light.bathroom_light
      - type: entities
        title: BMW 330e
        show_header_toggle: false
        entities:
          - script.bmw_airco
          - script.bmw_horn
          - script.bmw_light
          - lock.330e_iperformance_lock
      - type: picture-entity
        title: BMW 330e
        entity: camera.bmw_330e
        camera_image: camera.bmw_330e
        show_info: true
        tap_action: dialog
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: Afvalwijzer
          show_header_toggle: false
        filter:
          include:
            - entity_id: sensor.cure_restafval
            - entity_id: sensor.cure_gft
            - entity_id: sensor.cure_papier
        sort:
          method: state
          reverse: true
  - title: Living Room
    icon: mdi:sofa
    cards:
      - type: entities
        title: Diner
        show_header_toggle: true
        entities:
          - light.diner_lamp
          - group.livingroom_tv_lights
          - group.ikea_lights
      - type: entities
        title: TV
        show_header_toggle: true
        entities:
          - input_select.harmony
      - type: media-control
        entity: media_player.apple_tv
  - title: Bureau
    icon: mdi:desk
    cards:
      - type: entities
        title: Bureau
        show_header_toggle: true
        entities:
          - group.bureau_lights
  - title: Bedroom
    icon: mdi:hotel
    cards:
      - type: entities
        title: Bedroom Light
        show_header_toggle: true
        entities:
          - light.slaapkamer_1
          - light.slaapkamer_2
      - type: entities
        title: Bedroom Sidelights
        show_header_toggle: true
        entities:
          - light.fabians_lamp
          - light.andreias_lamp
  - title: Kitchen
    icon: mdi:stove
    cards:
      - type: entities
        title: Kitchen Light
        show_header_toggle: true
        entities:
          - light.kitchen_2
          - light.kitchen_1
          - light.kitchen_3
  - title: Entrance
    icon: mdi:door-open
    cards:
      - type: entities
        title: Entrance
        show_header_toggle: true
        entities:
          - light.entrance_lamp
          - light.toilet_light
  - title: BMW 330e
    icon: mdi:car
    cards:
      - type: entities
        entities:
          - binary_sensor.330e_iperformance_door_lock_state
          - binary_sensor.330e_iperformance_lids
          - binary_sensor.330e_iperformance_windows
          - sensor.330e_iperformance_charging_level_hv
          - sensor.charge_status
          - sensor.330e_iperformance_charging_time_remaining
          - sensor.330e_iperformance_remaining_range_total
          - sensor.330e_iperformance_mileage
      - type: entities
        title: BMW 330e
        show_header_toggle: false
        entities:
          - script.bmw_airco
          - script.bmw_horn
          - script.bmw_light
          - lock.330e_iperformance_lock
      - type: picture-entity
        title: BMW 330e
        entity: camera.bmw_330e
        camera_image: camera.bmw_330e
        show_info: true
        tap_action: dialog