---
button_card_templates: !include_dir_merge_named "/config/custom_components/ui_lovelace_minimalist/__ui_minimalist__/ulm_templates/"

title: "iHouse"
theme: "minimalist-desktop"
background: "var(--background-image)"
# views: !include_dir_merge_list "views/"
views:
  ### VISIBLE VIEWS
  # Mainfdsd
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_main.yaml
  # Climate
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_climate.yaml
  # Lights
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_lights.yaml
  # Shutters
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_shutters.yaml

  # Cameras
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_cameras.yaml
  # Media
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_media.yaml
  # Energy
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_energy_day.yaml
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_energy_week.yaml
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_energy_month.yaml
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_energy_year.yaml
  # Security
  - !include /config/ui_lovelace_minimalist/dashboard/tabs/view_security.yaml
