############# MOVE FROM "custom_updater" TO "HACS"!!! ##########################
## https://custom-components.github.io/hacs/
## BASICALLY YOU NEED TO ADD EVERY CUSTOM REPO TO HACS 
## AND CHANGE ALL URL FROM:" /customcards/custom_lovelace_cards/XXXXXXXXX"
## TO "/community_plugin/XXXXXXXXX/XXXXXXXXX.js" 
## More info at: https://custom-components.github.io/hacs/#add-custom-repos
################################################################################

#################################################################
#                             JS                                #
################################################################# 
resources: 
## https://github.com/thomasloven/lovelace-card-modder 
  - url: /community_plugin/lovelace-card-modder/card-modder.js
    type: js
## https://github.com/thomasloven/lovelace-card-tools
  - url: /community_plugin/lovelace-card-tools/card-tools.js    
    type: js
  - url: /community_plugin/lovelace-auto-entities/auto-entities.js
    type: module
    
title: iHouse
views:
  - title: default_view
    icon: mdi:home
    cards:
      - type: entities
        title: Entrance
        show_header_toggle: true
        entities:
          - camera.front_door
          - light.entrance_lamp
      - type: entities
        title: Living Room
        show_header_toggle: true
        entities:
          - light.diner_lamp
          - group.livingroom_tv_lights
          - group.ikea_lights
      - type: entities
        title: Bureau
        show_header_toggle: true
        entities:
          - group.bureau_lights
      - type: entities
        title: Kitchen
        show_header_toggle: true
        entities:
          - group.kitchen_lights
      - type: entities
        title: Bedroom
        show_header_toggle: true
        entities:
          - group.bedroom_sidelights_group
      - type: entities
        title: Bathroom
        show_header_toggle: true
        entities:
          - light.bathroom_light
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          title: Afvalwijzer
          show_header_toggle: false
        filter:
          include:
            - entity_id: sensor.restafval
            - entity_id: sensor.gft
            - entity_id: sensor.papier
        sort:
          method: state
          reverse: true
  - title: Living Room
    icon: mdi:sofa
    cards:
      - type: vertical-stack
        cards:
        - type: entities
          title: Living Room
          show_header_toggle: true
          entities:
            - group.livingroom_tv_lights
            - group.ikea_lights
            - switch.floorlight
            - light.diner_lamp
        - type: entities
          title: TV
          show_header_toggle: false
          entities:
            - input_select.harmony
        - type: media-control
          entity: media_player.apple_tv
      - type: vertical-stack
        cards:
        - type: entities
          title: Kitchen
          show_header_toggle: true
          entities:
            - group.kitchen_lights
        - type: glance
          title: Doors
          entities:
            - binary_sensor.kitchen_door_state
            - binary_sensor.garden_door_state
  - title: Bureau
    icon: mdi:desk
    cards:
      - type: entities
        title: Bureau
        show_header_toggle: true
        entities:
          - group.bureau_lights
  - title: Bedroom
    icon: mdi:hotel
    cards:
      - type: entities
        title: Bedroom
        show_header_toggle: true
        entities:
          - light.slaapkamer_1
          - light.slaapkamer_2
          - cover.bedroom_shutter
      - type: entities
        title: Bedroom Sidelights
        show_header_toggle: true
        entities:
          - light.fabians_lamp
          - light.andreias_lamp
  - title: Entrance
    icon: mdi:door-open
    cards:
      - type: entities
        title: Entrance
        show_header_toggle: true
        entities:
          - light.entrance_lamp
          - light.toilet_light
  - title: Tesla
    icon: mdi:car
    cards:
      - type: entities
        entities:
          - binary_sensor.sonic_charger_sensor
          - climate.sonic_hvac_climate_system
          - lock.sonic_door_lock
          - lock.sonic_charger_door_lock
          - switch.sonic_charger_switch
          - sensor.sonic_battery_sensor
          - sensor.sonic_mileage_sensor
          - sensor.sonic_range_sensor
      - type: map
        aspect_ratio: 16:9
        default_zoom: 14
        entities:
          - device_tracker.tesla_model_3_594222_location_tracker