sensor:
  - platform: template
    sensors:
      ############################################################################
      #                                                                          #
      #   Bedroom                                                                #
      #                                                                          #
      ############################################################################

      weather_ihouse_current_temp:
        friendly_name: "Weather Current Temp"
        icon_template: mdi:thermometer
        unit_of_measurement: "°C"
        value_template: >-
          {{ state_attr('weather.ihouse', 'temperature') }}
