type: vertical-stack
cards:

############################################################################
#                                                                          #
#   Title                                                                  #
#                                                                          #
############################################################################

  - type: horizontal-stack
    cards:
      
      - type: custom:decluttering-card
        template: title_button_card
        variables:
          - name: PC Automation


############################################################################
#                                                                          #
#   Scripts                                                                #
#                                                                          #
############################################################################

  - type: horizontal-stack
    cards:          

      - type: custom:decluttering-card # DIMKA Auto Sleep
        template: light_button
        variables:
          - entity: input_boolean.automation_dimka_sleep
          - name: DIMKA Sleep
          - icon: mdi:flash-auto
          - cust_2_field: "Automation"

      - type: "custom:button-card"
        color_type: blank-card   
        
      - type: "custom:button-card"
        color_type: blank-card

  - !include /config/lovelace/styles/separator_card.yaml
