sensor:
  - platform: template
    sensors:
      ############################################################################
      #                                                                          #
      #   Living Room TV                                                         #
      #                                                                          #
      ############################################################################

      living_room_tv:
        friendly_name: "Activity"
        value_template: >
          {% if states.remote.harmony_living_room.attributes.current_activity == "PowerOff" %}
              Off
          {% else %}
              {{ states.remote.harmony_living_room.attributes.current_activity }}
          {% endif %}
