- alias: Afval notificatie - gft
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: numeric_state
    entity_id: sensor.eindhoven_biodegradable_waste_countdown
    below: 2
    above: 0
  action:
    - service: notify.pushover
      data:
        title: "Afval"
        message: "Morgen: Groene bak"