- platform: template
  sensors:
    current_activity:
      friendly_name: 'Current Activity'
      value_template: '{{ states.remote.harmonyhub.attributes.current_activity }}'
      
- platform: template
  sensors:
     charge_status:
       friendly_name: "Charge Status"
       value_template: >-
          {% if is_state('sensor.330e_iperformance_charging_status', 'ChargingState.FINISHED_FULLY_CHARGED') %}
            Full
          {% elif is_state('sensor.330e_iperformance_charging_status', 'ChargingState.CHARGING') %}
            Charging
          {% else %}
            Not Charging
          {% endif %}
       icon_template: >-
           {% if states.sun.sun.attributes.elevation > 10 %}
             mdi:weather-sunny
           {% elif states.sun.sun.attributes.elevation < 10 and states.sun.sun.attributes.azimuth < 180 %}
             mdi:weather-sunset-up
           {% elif states.sun.sun.attributes.elevation < 10 and states.sun.sun.attributes.azimuth > 180 %}
             mdi:weather-sunset-down
           {% else %}
            mdi:weather-sunset
           {% endif %}
- platform: yr