- platform: template
  switches:
        # TV HARMONY ACTIVITY
        turn_on_tv:
          friendly_name: TV
          value_template: "{{ is_state_attr('remote.harmonyhub', 'current_activity', 'TV') }}"
          turn_on:
            service: remote.turn_on
            data:
              entity_id: remote.harmonyhub
              activity: 'TV'
          turn_off:
            service: remote.turn_off
            data:
              entity_id: remote.harmonyhub
              activity: 'PowerOff'
        
        # MOVIES HARMONY ACTIVITY
        turn_on_atv:
          friendly_name: Movies
          value_template: "{{ is_state_attr('remote.harmonyhub', 'current_activity', 'Movies') }}"
          turn_on:
            service: remote.turn_on
            data:
              entity_id: remote.harmonyhub
              activity: 'Movies'
          turn_off:
            service: remote.turn_off
            data:
              entity_id: remote.harmonyhub
              activity: 'PowerOff'
        
        # MAC MINI HARMONY ACTIVITY
        turn_on_mac:
          friendly_name: View Mac mini
          value_template: "{{ is_state_attr('remote.harmonyhub', 'current_activity', 'View Mac mini') }}"
          turn_on:
            service: remote.turn_on
            data:
              entity_id: remote.harmonyhub
              activity: 'View Mac mini'
          turn_off:
            service: remote.turn_off
            data:
              entity_id: remote.harmonyhub
              activity: 'PowerOff'