# Koppeling van de Connectix.nl slimme meter via WiFi adapter
sensor:
  # Calculate Remaining Power
  - platform: template
    sensors:
      actual_consumption:
        value_template: >
          {{ '%0.2f' | format(states.sensor.power_consumption.state | float - 
                              states.sensor.power_production.state | float) }}
        unit_of_measurement: "kW"
        friendly_name: Echt verbruik (kW)
  - platform: template
    sensors:
      actual_consumption_kwh:
        value_template: >
          {{ '%0.2f' | format((states.sensor.energy_consumption_tarif_1.state | float + 
                              states.sensor.energy_consumption_tarif_2.state | float) - 
                              (states.sensor.energy_production_tarif_1.state | float + 
                              states.sensor.energy_production_tarif_2.state | float)) }}
        unit_of_measurement: "kWh"
        friendly_name: Echt verbruik (kWh)

utility_meter:
  daily_energy_meter:
    source: sensor.actual_consumption_kwh
    cycle: daily
    net_consumption: true
  monthly_energy_meter:
    source: sensor.actual_consumption_kwh
    cycle: monthly
    net_consumption: true
  daily_gas_meter:
    source: sensor.gas_consumption
    cycle: daily
  monthly_gas_meter:
    source: sensor.gas_consumption
    cycle: monthly
