sensor:
  - platform: template
    sensors:
      ############################################################################
      #                                                                          #
      #   Bedroom                                                                #
      #                                                                          #
      ############################################################################

      airconditioner_bedroom_operation_mode:
        friendly_name: "Airconditioner Bedroom Operation Mode"
        icon_template: mdi:thermostat
        value_template: >-
          {% if is_state('climate.airconditioner_bedroom', 'heat_cool') %}
            Auto
          {% elif is_state('climate.airconditioner_bedroom', 'cool') %}
            Cool
          {% elif is_state('climate.airconditioner_bedroom', 'dry') %}
            Droog
          {% elif is_state('climate.airconditioner_bedroom', 'fan_only') %}
            Ventilator
          {% elif is_state('climate.airconditioner_bedroom', 'heat') %}
            Heat
          {% else %}
            Uit
          {% endif %}

      airconditioner_bedroom_current_temp:
        friendly_name: "Airconditioner Bedroom Temperature"
        unit_of_measurement: "°C"
        icon_template: mdi:thermometer
        value_template: >-
          {{ state_attr('climate.airconditioner_bedroom', 'current_temperature') }}

      airconditioner_bedroom_target_temp:
        friendly_name: "Airconditioner Bedroom Target Temperature"
        icon_template: mdi:thermometer
        value_template: >-
          {{ state_attr('climate.airconditioner_bedroom', 'temperature') }}

      airconditioner_bedroom_fan_mode:
        friendly_name: "Airconditioner Bedroom Fan"
        icon_template: mdi:hvac
        value_template: >-
          {{ state_attr('climate.airconditioner_bedroom', 'fan_mode') }}

      airconditioner_bedroom_swing_mode:
        friendly_name: "Airconditioner Bedroom Swing Mode"
        icon_template: mdi:hvac
        value_template: >-
          {{ state_attr('climate.airconditioner_bedroom', 'swing_mode') }}

      outside_temperature:
        friendly_name: "Outside Temperature"
        unit_of_measurement: "°C"
        icon_template: mdi:thermometer
        value_template: >-
          {{ state_attr('weather.forecast_home', 'temperature') }}

binary_sensor:
  - platform: template
    sensors:
      airconditioner_bedroom_state:
        friendly_name: "Airconditioner Bedroom State"
        value_template: "{{ not is_state('climate.airconditioner_bedroom','off') }}"