esphome:
  name: watersensor

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "sl25/ZW4gKs0wL0MEDZiUq96DA36B2BsoiSXYnyhLM0="

ota:
  password: "25c79b75ac06bfd84ad7a724de9cb7cf"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Watersensor Fallback Hotspot"
    password: "iYQm5TKahlXj"

captive_portal:
    
sensor:
- platform: pulse_counter
  pin: GPIO12
  update_interval : 6s
  name: "water pulse"
  id: water_pulse

- platform: pulse_meter
  pin: GPIO12
  name: "Water Pulse Meter"
  unit_of_measurement: "liter/min"
  icon: "mdi:water"
  total:
    name: "Water Total"
    unit_of_measurement: "L"
    device_class: water
    state_class: total_increasing

- platform: template
  name: "Water Usage Liter"
  id: water_flow_rate
  accuracy_decimals: 1
  unit_of_measurement: "l/min"
  icon: "mdi:water"
  lambda: return (id(water_pulse).state * 10);
  update_interval: 6s