#Enables HassIO
hassio:

# Checks for available updates
updater:

#Enables lovelace
lovelace:
  mode: yaml

# Enables configuration UI
config:
  
# Enables the frontend
frontend:
  # Add themes
  themes: !include_dir_merge_named ../themes
  # Enable ES6 features
  javascript_version: latest

    
# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Settings for http requests
http:
  ssl_certificate: /ssl/certificate.pem
  ssl_key: /ssl/privkey.pem
  cors_allowed_origins:
    - http://192.168.1.10:7080
  trusted_proxies: 172.16.0.0/12
  use_x_forwarded_for: true
  ip_ban_enabled: false
  login_attempts_threshold: 3

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - groups

#HassIO Comunity Store
hacs:
  token: !secret hacs_token