frontend:
  themes: !include_dir_merge_named /config/themes

#Enable Cloud
cloud:

#Enables lovelace
lovelace:
  mode: yaml
  resources: !include /config/resources.yaml
  # dashboards:
  #   lovelace-minimalist:
  #     mode: yaml
  #     filename: /config/ui-lovelace.yaml
  #     title: "iHouse"
  #     icon: mdi:view-dashboard
  #     show_in_sidebar: true
  #     require_admin: false

sensor:
  - platform: template
    sensors:
      placeholder:
        value_template: " "

# Enables configuration UI
config:

zeroconf:

conversation:

my:

energy:

media_source:

input_number:
input_text:
input_datetime:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Settings for http requests
http:
  # ssl_certificate: /ssl/fullchain.pem
  # ssl_key: /ssl/privkey.pem
  #   cors_allowed_origins:
  #     - http://192.168.1.10:7080
  trusted_proxies:
    - 192.168.1.50
    - 192.168.1.111
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - groups

python_script:
