frontend:
  themes: !include_dir_merge_named /config/themes

#Enable Cloud
cloud:

# Checks for available updates
updater:

  #Enables lovelace
lovelace:
  mode: yaml
  resources: !include /config/lovelace/resources.yaml
  dashboards:
    lovelace-system:
      mode: yaml
      filename: ui-system.yaml
      title: "System"
      icon: mdi:view-dashboard
      show_in_sidebar: true
      require_admin: false
    lovelace-wallpanel:
      mode: yaml
      filename: ui-wallpanel.yaml
      title: "Wall Panel"
      icon: mdi:view-dashboard
      show_in_sidebar: true
      require_admin: false

sensor:
  - platform: template
    sensors:
      placeholder:
        value_template: " "

# Enables configuration UI
config:

browser_mod:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Settings for http requests
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  #   cors_allowed_origins:
  #     - http://192.168.1.10:7080
  #   trusted_proxies: 172.16.0.0/12
  #   use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - groups
