#Enables HassIO
# hassio:

# Checks for available updates
updater:

#Enables lovelace
lovelace:
  mode: storage
  resources:
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/lovelace-hui-element/hui-element.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/Homekit-panel-card/homekit-panel-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /browser_mod.js
      type: module
    - url: /local/font.css
      type: css

sensor:
  - platform: template
    sensors:
      placeholder:
        value_template: " "

# Enables configuration UI
config:

browser_mod:

# Track the sun
sun:

# Text to speech
tts:
  - platform: google_translate
# Allows you to issue voice commands from the frontend in enabled browsers
# conversation:

# Settings for http requests
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  #   cors_allowed_origins:
  #     - http://192.168.1.10:7080
  #   trusted_proxies: 172.16.0.0/12
  #   use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5

# View all events in a logbook
logbook:

# Enables support for tracking state changes over time
history:
  exclude:
    domains:
      - groups
#HassIO Comunity Store
# hacs:
#   token: !secret hacs_token
