sensor:
    - platform: afvalbeheer
      wastecollector: Cure
      resources:
        - restafval
        - gft
        - papier
        - pmd
      postcode: !secret afvalwijzer_postcode
      streetnumber: !secret afvalwijzer_huisnummer
      upcomingsensor: 0
      dateformat: '%d-%m-%Y'
      dateonly: 0
      name: ''
      nameprefix: 1
      builtinicons: 0
      dutch: 1