sensor:
  - platform: afvalwijzer
    provider: mijnafvalwijzer # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: 5627GG # (required, default = '')
    street_number: 12 # (required, default = '')
    suffix: "" # (optional, default = '')
    exclude_pickup_today: false # (optional, default = true) to take or not to take Today into account in the next pickup.
    default_label: Geen # (optional, default = Geen) label if no date found
    id: "" # (optional, default = '') use if you'd like to have multiple waste pickup locations in HASS
    exclude_list: "" # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"

  - platform: template
    sensors:
      afvalwijzer_next_item_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_next_item', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_next_item', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_next_item', 'pmd') %}PMD
          {% elif is_state('sensor.afvalwijzer_next_item', 'restafval') %}Restafval
          {% else %}Geen
          {% endif %}
        friendly_name: "Next pickup item"

      afvalwijzer_today_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_today', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_today', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_today', 'pmd') %}PMD
          {% elif is_state('sensor.afvalwijzer_today', 'restafval') %}Restafval
          {% else %}Geen
          {% endif %}
        friendly_name: "Vandaag"

      afvalwijzer_tomorrow_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_tomorrow', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_tomorrow', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_tomorrow', 'pmd') %}PMD
          {% elif is_state('sensor.afvalwijzer_tomorrow', 'restafval') %}Restafval
          {% else %}Geen
          {% endif %}
        friendly_name: "Morgen"

      afvalwijzer_day_after_tomorrow_formatted:
        value_template: >-
          {% if is_state('sensor.afvalwijzer_day_after_tomorrow', 'gft') %}GFT
          {% elif is_state('sensor.afvalwijzer_day_after_tomorrow', 'papier') %}Papier
          {% elif is_state('sensor.afvalwijzer_day_after_tomorrow', 'pmd') %}PMD
          {% elif is_state('sensor.afvalwijzer_day_after_tomorrow', 'restafval') %}Restafval
          {% else %}Geen
          {% endif %}
        friendly_name: "Overmorgen"

ios:
  push:
    categories:
      - name: Afval
        identifier: "afval"
        actions:
          - identifier: "MARK_TRASH_MOVED"
            title: "Afval verwerkt"
            activationMode: "background"
            authenticationRequired: no
            destructive: yes
            behavior: "default"
